name: OWASP Dependency Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  vulnerability-check:
    name: Checks Project's Dependencies for Vulnerabilities
    runs-on: [self-hosted, Linux, X64, docker]
    timeout-minutes: 45
    steps:
      - name: Checkout Project Sources
        id: checkout-project-sources
        uses: actions/checkout@v5
      - name: Setup Java as Corretto 21
        id: setup-java-corretto-21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Setup Gradle Build Action
        id: action-setup-gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.14.3'
      - name: Run Gradle Build Command
        id: run-gradle-build-cmd
        run: ./gradlew build --exclude-task test --exclude-task check --exclude-task cleanIdea --exclude-task ideaModule
      - name: Run Gradle CVE Check Command
        id: run-gradle-cve-check-cmd
        run: ./gradlew dependencyCheckAnalyze --exclude-task cleanIdea --exclude-task ideaModule
